# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: managerservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14managerservice.proto\x12\x0emanagerservice\":\n\rBrokerDetails\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"\x16\n\x05Query\x12\r\n\x05query\x18\x01 \x01(\t\"\x1f\n\x0eReplicaDetails\x12\r\n\x05token\x18\x01 \x01(\t\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\t\n\x07Request\"\n\n\x08Response\"\x0b\n\tHeartBeat2\xf6\x02\n\x0eManagerService\x12I\n\x0eRegisterBroker\x12\x1d.managerservice.BrokerDetails\x1a\x16.managerservice.Status\"\x00\x12\x45\n\x0bHealthCheck\x12\x19.managerservice.HeartBeat\x1a\x19.managerservice.HeartBeat\"\x00\x12L\n\x0fRegisterReplica\x12\x1e.managerservice.ReplicaDetails\x1a\x15.managerservice.Query\"\x00\x30\x01\x12\x42\n\x0bPushUpdates\x12\x15.managerservice.Query\x1a\x18.managerservice.Response\"\x00(\x01\x12@\n\nGetUpdates\x12\x17.managerservice.Request\x1a\x15.managerservice.Query\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'managerservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BROKERDETAILS._serialized_start=40
  _BROKERDETAILS._serialized_end=98
  _QUERY._serialized_start=100
  _QUERY._serialized_end=122
  _REPLICADETAILS._serialized_start=124
  _REPLICADETAILS._serialized_end=155
  _STATUS._serialized_start=157
  _STATUS._serialized_end=181
  _REQUEST._serialized_start=183
  _REQUEST._serialized_end=192
  _RESPONSE._serialized_start=194
  _RESPONSE._serialized_end=204
  _HEARTBEAT._serialized_start=206
  _HEARTBEAT._serialized_end=217
  _MANAGERSERVICE._serialized_start=220
  _MANAGERSERVICE._serialized_end=594
# @@protoc_insertion_point(module_scope)
